name: First Work Flow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print A Welcome Message
        run: echo "Welcome Sir!"

      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: List Files
        run: ls -la
